apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "platform-membrane.fullname" . }}-api
spec:
  podSelector:
    matchLabels:
      app: platform-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.api.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: platform-postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app: platform-redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              app: platform-minio
      ports:
        - protocol: TCP
          port: 9000
