apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-membrane.fullname" . }}-api
type: Opaque
stringData:
  PLATFORM_MASTER_API_KEY: {{ required "secrets.masterApiKey must be set at install time" .Values.secrets.masterApiKey | quote }}
