[pytest]
testpaths = tests tests_integration
norecursedirs =
    .git
    archive
    build
    dist
    external
    lab/fixtures
    tmp
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
