import { defineConfig } from 'vitest/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      '@aaes-os/architect-agent': path.join(rootDir, 'packages/architect-agent/src/index.ts'),
      '@aaes-os/runledger': path.join(rootDir, 'packages/runledger/src/index.ts'),
      '@aaes-os/aaes-governance': path.join(rootDir, 'packages/aaes-governance/src/index.ts'),
      '@aaes-os/trace-bus': path.join(rootDir, 'packages/trace-bus/src/index.ts'),
      '@aaes-os/ucr-runtime': path.join(rootDir, 'packages/ucr-runtime/src/index.ts'),
      '@aaes-os/tri-core-protocol': path.join(rootDir, 'packages/tri-core-protocol/src/index.ts'),
      '@aaes-os/mri-instrument': path.join(rootDir, 'packages/mri-instrument/src/index.ts'),
      '@aaes-os/trust-root': path.join(rootDir, 'packages/trust-root/src/index.ts'),
      '@aaes-os/ucr-attestation': path.join(rootDir, 'packages/ucr-attestation/src/index.ts'),
      '@aaes-os/runtime-law-spine': path.join(rootDir, 'packages/runtime-law-spine/src/index.ts'),
      '@aaes-os/evidence-receipts': path.join(rootDir, 'packages/evidence-receipts/src/index.ts'),
      '@aaes-os/lirl': path.join(rootDir, 'packages/lirl/src/index.ts'),
      '@aaes-os/constitutional-enforcement-node': path.join(rootDir, 'packages/constitutional-enforcement-node/src/index.ts'),
      '@aaes-os/meta-constitutional-calculus': path.join(rootDir, 'packages/meta-constitutional-calculus/src/index.ts'),
      '@aaes-os/transition-validation-pipeline': path.join(rootDir, 'packages/transition-validation-pipeline/src/index.ts'),
      '@aaes-os/sovereignty-ledger': path.join(rootDir, 'packages/sovereignty-ledger/src/index.ts'),
      '@aaes-os/invariant-registry': path.join(rootDir, 'packages/invariant-registry/src/index.ts'),
      '@aaes-os/nimf': path.join(rootDir, 'packages/nimf/src/index.ts'),
      '@aaes-os/constitutional-evolution': path.join(rootDir, 'packages/constitutional-evolution/src/index.ts'),
      '@aaes-os/omega-stress-harness': path.join(rootDir, 'packages/omega-stress-harness/src/index.ts'),
      '@aaes-os/governed-runtime': path.join(rootDir, 'packages/governed-runtime/src/index.ts'),
      '@aaes-os/nova-shell': path.join(rootDir, 'packages/nova-shell/src/index.ts'),
      '@aaes-os/infinity-agents': path.join(rootDir, 'packages/infinity-agents/src/index.ts'),
      '@aaes-os/sandbox': path.join(rootDir, 'packages/sandbox/src/index.ts'),
      '@aaes-os/coding-assistant': path.join(rootDir, 'packages/coding-assistant/src/index.ts'),
      '@aaes-os/sovren': path.join(rootDir, 'packages/sovren/src/index.ts'),
      '@aaes-os/kerno': path.join(rootDir, 'packages/kerno/src/index.ts'),
      '@aaes-os/federation': path.join(rootDir, 'packages/federation/src/index.ts'),
      '@aaes-os/nova-substrate-client': path.join(rootDir, 'packages/nova-substrate-client/src/index.ts'),
      '@aaes-os/coda-doc': path.join(rootDir, 'packages/coda-doc/src/index.ts'),
      '@aaes-os/isl-runtime': path.join(rootDir, 'packages/isl-runtime/src/index.ts'),
      '@aaes-os/gcre-sysmin': path.join(rootDir, 'packages/gcre-sysmin/src/index.ts'),
      '@aaes-os/nova-coda': path.join(rootDir, 'packages/nova-coda/src/index.ts'),
      '@aaes-os/coda-runtime': path.join(rootDir, 'packages/coda-runtime/src/index.ts'),
      '@aaes-os/platform-core': path.join(rootDir, 'packages/platform-core/src/index.ts'),
      '@aaes-os/platform-mesh': path.join(rootDir, 'packages/platform-mesh/src/index.ts'),
      '@aaes-os/psom-mesh': path.join(rootDir, 'packages/psom-mesh/src/index.ts'),
      '@aaes-os/sgce': path.join(rootDir, 'packages/sgce/src/index.ts'),
      '@aaes-os/operator-config': path.join(rootDir, 'packages/operator-config/src/index.ts'),
      '@aaes-os/platform-sdk': path.join(rootDir, 'packages/platform-sdk/src/index.ts'),
      '@aaes-os/aais': path.join(rootDir, 'packages/aais/src/index.ts'),
      '@aaes-os/sovereignx-router': path.join(rootDir, 'packages/sovereignx-router/src/index.ts'),
      '@aaes-os/canonical-replay-matrix': path.join(rootDir, 'packages/canonical-replay-matrix/src/index.ts'),
      '@aaes-os/canonical-authority-matrix': path.join(rootDir, 'packages/canonical-authority-matrix/src/index.ts'),
      '@aaes-os/evidence-federation-ledger': path.join(rootDir, 'packages/evidence-federation-ledger/src/index.ts'),
      '@aaes-os/evidence-lineage-ledger': path.join(rootDir, 'packages/evidence-lineage-ledger/src/index.ts'),
      '@aaes-os/canonical-stewardship-matrix': path.join(rootDir, 'packages/canonical-stewardship-matrix/src/index.ts'),
      '@aaes-os/canonical-temporal-grid': path.join(rootDir, 'packages/canonical-temporal-grid/src/index.ts'),
      '@aaes-os/evidence-sovereign-ledger': path.join(rootDir, 'packages/evidence-sovereign-ledger/src/index.ts'),
    },
  },
  test: {
    include: [
      'tests/integration/**/*.test.ts',
      'tests/model/**/*.test.ts',
      'tests/release/**/*.test.ts',
      'packages/**/src/**/*.test.ts',
      'services/**/src/**/*.test.ts',
      'services/**/src/**/*.test.tsx',
    ],
    environment: 'node',
  },
});
