export default {
  docs: [
    'overview',
    {
      type: 'category',
      label: 'Governance',
      items: [
        'governance/constitutional-laws-of-intelligence',
        'governance/crec',
        'governance/constitutional-release-receipt',
        'governance/doctrine',
        'governance/invariants',
        'governance/ledger',
        'governance/fault-journal',
        'governance/tri-core',
        'governance/governance-loop',
      ],
    },
    {
      type: 'category',
      label: 'AAES-OS Specifications',
      items: [
        'specifications/index',
        'specifications/aaes-os-v1-implementation-slice',
        'specifications/aaes-os-api-reference-stabilization',
        'specifications/aaes-os-governance-traceability',
        'specifications/aaes-os-example-path-cleanup',
        'specifications/aaes-os-engineering-handbook',
        'specifications/aaes-os-engineering-specification',
        'specifications/aaes-os-engineering-standards',
        'specifications/aaes-os-governance-specification',
        'specifications/aaes-os-product-roadmap',
        'specifications/ugr-ugql-upl-crf-specification',
      ],
    },
    {
      type: 'category',
      label: 'CRK1 Release',
      items: [
        'crk1/release/ugr-ugql-upl-crf-v1-conformance',
      ],
    },
    {
      type: 'category',
      label: 'VEILTHORN',
      items: [
        'veilthorn/index',
        'veilthorn/quick-start',
        'veilthorn/api-reference',
        'veilthorn/proof-surface',
        'veilthorn/examples',
        'veilthorn/conformance',
      ],
    },
    {
      type: 'category',
      label: 'Runtime',
      items: [
        'runtime/runtime-core',
        {
          type: 'category',
          label: 'Live Surfaces',
          items: [
            'runtime/live-surfaces',
            'runtime/coda-doc',
            'runtime/coda-runtime',
            'runtime/nova-coda',
            'runtime/nova-substrate',
            'runtime/nova-substrate-client',
            'runtime/ul-runtime',
            'runtime/csl-runtime',
            'runtime/isl-runtime',
            'runtime/cic-runtime',
            'runtime/ccc-runtime',
            'runtime/coe-runtime',
            'runtime/cml-voss-runtime',
            'runtime/ugr-runtime',
            'runtime/gcre-sysmin',
          ],
        },
        'runtime/node-v0-1',
        'runtime/nova-shell',
        'runtime/sovereign-ide',
        'runtime/substrate',
      ],
    },
    {
      type: 'category',
      label: 'Visualizers',
      items: ['visualizer/governance-dashboard', 'visualizer/sovereign-ide'],
    },
    {
      type: 'category',
      label: 'Agents',
      items: ['agents/infinity-agents', 'agents/aais', 'agents/aais-capabilities', 'agents/aais-routing-analytics', 'agents/urg'],
    },
    {
      type: 'category',
      label: 'ULX',
      items: ['ulx/ul-verb-language', 'ulx/ulx-language', 'ulx/ulx-vm', 'ulx/ulx-governance', 'ulx/ulx-language-registry', 'ulx/ulx-ide-integration'],
    },
  ],
};
