'use client';
import{useCallback,useEffect,useMemo,useState}from'react';import styles from'./twin.module.css';
type KernelEvent={id:string;type:'INTENT_ACCEPTED'|'PLAN_APPROVED'|'EXECUTION_AUTHORIZED'|'STEP_COMPLETED'|'EVIDENCE_ACCEPTED'|'USS_UPDATED';actorId:string;timestamp:string;planId?:string;stepId?:string;evidenceId?:string};
type GraphResult={nodes:Array<Record<string,unknown>>;edges:Array<{from:string;to:string;type:string}>};
export interface TwinPersonalityProfile{twinId:string;traits:{name:string;weight:number}[];style:{tone:string;riskTolerance:string;explorationBias:string};updatedAt:string}
export interface SubstrateMetrics{substrateId:string;invocations:number;avgLatencyMs:number;errorRate:number;evidencePerInvocation:number}
const api=process.env.NEXT_PUBLIC_RUNTIME_API??'';
const ceipStages=['Intent','Constitutional Context','Institutional Memory Discovery','Evidence Discovery','Constitutional Planning','Risk Assessment','Constitutional Decision','Human Approval','Execution','Evidence Package','Constitutional Receipt','Replay','Conformance','Knowledge Admission','UGR Institutional Memory','Pattern Discovery','Constitutional Recommendation','Executive Intelligence','Audit'];
async function post<T>(path:string,body:unknown):Promise<T>{const response=await fetch(`${api}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`${path} returned ${response.status}`);return response.json() as Promise<T>;}
const demoEvents:KernelEvent[]=[{id:'evt-6',type:'USS_UPDATED',actorId:'jon',timestamp:'2026-07-14T13:24:20Z',evidenceId:'ev-003'},{id:'evt-5',type:'EVIDENCE_ACCEPTED',actorId:'jon',timestamp:'2026-07-14T13:24:15Z',evidenceId:'ev-002'},{id:'evt-4',type:'STEP_COMPLETED',actorId:'jon',timestamp:'2026-07-14T13:24:10Z',stepId:'step-AnalyzeMetrics'},{id:'evt-3',type:'EXECUTION_AUTHORIZED',actorId:'jon',timestamp:'2026-07-14T13:24:04Z',planId:'plan-intent-001'},{id:'evt-2',type:'PLAN_APPROVED',actorId:'jon',timestamp:'2026-07-14T13:24:03Z',planId:'plan-intent-001'},{id:'evt-1',type:'INTENT_ACCEPTED',actorId:'jon',timestamp:'2026-07-14T13:24:00Z'}];
export default function TwinConsole(){const[events,setEvents]=useState<KernelEvent[]>(demoEvents);const[connected,setConnected]=useState(false);const[notice,setNotice]=useState('Live endpoint not connected — showing reference evidence.');const[graphs,setGraphs]=useState<Record<string,GraphResult>>({});const load=useCallback(async(graph:string)=>{try{const value=await post<GraphResult>('/uss/query',{graph,filter:{actorId:'jon'}});setGraphs(v=>({...v,[graph]:value}));setNotice(`${graph} refreshed from USS.`);}catch{setNotice(`USS is unavailable; retained the last ${graph} projection.`);}},[]);useEffect(()=>{const base=process.env.NEXT_PUBLIC_EVENTS_URL;if(!base)return;const socket=new WebSocket(base);socket.onopen=()=>{setConnected(true);setNotice('Constitutional event stream connected.');};socket.onmessage=message=>{const event=JSON.parse(String(message.data)) as KernelEvent;setEvents(previous=>[event,...previous].slice(0,80));};socket.onclose=()=>setConnected(false);return()=>socket.close();},[]);const progress=useMemo(()=>new Set(events.map(e=>e.type)).size, [events]);return <main className={styles.page}>
<header className={styles.header}><div><p className={styles.eyebrow}>AI TWIN / JON-TWIN</p><h1>Constitutional operations console</h1><p className={styles.sub}>Every action remains visible from intent through governed state.</p></div><div className={styles.connection}><span className={connected?styles.live:styles.demo}/><strong>{connected?'LIVE MESH':'REFERENCE MODE'}</strong><small>{notice}</small></div></header>
<section className={styles.identity}><article><span>IDENTITY</span><strong>jon-twin</strong><small>First-class governed actor</small></article><article><span>AUTHORITY</span><strong>Advisor · Executor</strong><small>Delegated by jon</small></article><article><span>SOVEREIGNTY</span><strong>Sales · Analytics</strong><small>No authority expansion</small></article><article><span>REPUTATION</span><strong>0.87</strong><small>Evidence-backed</small></article></section>
<section className={styles.layout}><article className={`${styles.panel} ${styles.mission}`}><PanelTitle code="01" title="Active mission"/><p className={styles.missionName}>Improve Q3 sales pipeline</p><div className={styles.progress}><i style={{width:'64%'}}/></div><div className={styles.row}><span>Goal progress</span><b>64%</b></div><button onClick={()=>void load('MissionGraph')}>Refresh mission graph</button></article>
<article className={`${styles.panel} ${styles.lifecycle}`}><PanelTitle code="02" title="Constitutional lifecycle"/><div className={styles.flow}>{['INTENT_ACCEPTED','PLAN_APPROVED','EXECUTION_AUTHORIZED','STEP_COMPLETED','EVIDENCE_ACCEPTED','USS_UPDATED'].map((type,index)=><div className={events.some(e=>e.type===type)?styles.done:''} key={type}><span>{String(index+1).padStart(2,'0')}</span><strong>{type.replaceAll('_',' ')}</strong><i/></div>)}</div><p>{progress}/6 constitutional stages observed</p></article>
<article className={`${styles.panel} ${styles.lifecycle}`}><PanelTitle code="CEIP 1.0" title="Reference workflow"/><div className={styles.flow} style={{gridTemplateColumns:'repeat(4,1fr)'}}>{ceipStages.map((stage,index)=><div className={index<12?styles.done:''} key={stage}><span>{String(index+1).padStart(2,'0')}</span><strong>{stage}</strong><i/></div>)}</div><p>12/19 stages linked · current: Conformance · inspectable objects: intent, context, memories, evidence, plan, decision, approval, execution, package, receipt, replay.</p></article>
<article className={`${styles.panel} ${styles.stream}`}><PanelTitle code="LIVE" title="Kernel events"/><div className={styles.eventList}>{events.map(e=><div key={e.id}><time>{new Date(e.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><span className={styles.eventType}>{e.type.replaceAll('_',' ')}</span><small>{e.evidenceId??e.stepId??e.planId??e.actorId}</small></div>)}</div></article>
<GraphPanel code="03" title="Evidence" graph="EvidenceGraph" data={graphs.EvidenceGraph} onLoad={load}/><GraphPanel code="04" title="Lineage" graph="LineageGraph" data={graphs.LineageGraph} onLoad={load}/>
<article className={styles.panel}><PanelTitle code="07" title="Personality profile"/><strong className={styles.big}>0.88</strong><p>Analytical bias. Personality informs selection but never expands authority.</p><button onClick={()=>setNotice('Personality editing requires an authenticated Twin API session.')}>Edit traits</button></article>
<article className={styles.panel}><PanelTitle code="08" title="Mission board"/><ul className={styles.substrates}><li><b>ACTIVE</b><span>Improve Q3 pipeline</span></li><li><b>BLOCKED</b><span>CRM scope</span></li><li><b>DONE</b><span>Analyze metrics</span></li></ul><button onClick={()=>void load('MissionGraph')}>Refresh board</button></article>
<article className={styles.panel}><PanelTitle code="09" title="Replay DVR"/><p>Scrub Mission, Evidence, and Lineage graphs through point-in-time USS snapshots.</p><button onClick={()=>setNotice('Replay uses POST /uss/replay with actor scope and timestamp.')}>Open replay</button></article>
<article className={styles.panel}><PanelTitle code="10" title="Operator tools"/><ul className={styles.substrates}><li><b>ISL</b><span>dry-run validation</span></li><li><b>CIEMS</b><span>profile preview</span></li><li><b>USS</b><span>graph visualization</span></li></ul><button onClick={()=>setNotice('Governance changes require constitutional-admin authority.')}>Preview governance</button></article>
<article className={styles.panel}><PanelTitle code="05" title="Multiverse"/><div className={styles.branches}><span>scenario-sales-q3</span><div><i/>moderate improvement</div><div><i/>strong improvement</div></div><button onClick={async()=>{try{await post('/uss/trajectory',{graph:'MultiverseGraph',rootScenarioId:'scenario-sales-q3',depth:3});setNotice('Trajectory refreshed from USS.');}catch{setNotice('Trajectory endpoint unavailable.');}}}>Explore depth 3</button></article>
<article className={styles.panel}><PanelTitle code="06" title="Substrate receipts"/><ul className={styles.substrates}><li><b>analytics-01</b><span>analytics · low risk</span></li><li><b>llm-oss-02</b><span>llm · medium risk</span></li><li><b>crm-01</b><span>crm-tool · medium risk</span></li></ul></article></section></main>}
function PanelTitle({code,title}:{code:string;title:string}){return <div className={styles.panelTitle}><span>{code}</span><h2>{title}</h2></div>}
function GraphPanel({code,title,graph,data,onLoad}:{code:string;title:string;graph:string;data?:GraphResult;onLoad:(g:string)=>Promise<void>}){return <article className={styles.panel}><PanelTitle code={code} title={title}/><strong className={styles.big}>{data?.nodes.length??(graph==='EvidenceGraph'?2:2)}</strong><p>{data?'nodes returned by USS':graph==='EvidenceGraph'?'accepted records in current chain':'evidence-backed evolution arcs'}</p><button onClick={()=>void onLoad(graph)}>Query {graph}</button></article>}
