import { createCipheriv, createDecipheriv, createHash, createHmac, createPublicKey, randomBytes, timingSafeEqual, verify } from 'node:crypto';
import { appendFile, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

const AUTHORIZATION_URL = 'https://accounts.google.com/o/oauth2/v2/auth';
const TOKEN_URL = 'https://oauth2.googleapis.com/token';
const REVOKE_URL = 'https://oauth2.googleapis.com/revoke';
const GOOGLE_CERTS_URL = 'https://www.googleapis.com/oauth2/v3/certs';
const DRIVE_URL = 'https://www.googleapis.com/drive/v3';
const UPLOAD_URL = 'https://www.googleapis.com/upload/drive/v3';
const DEFAULT_SCOPES = 'openid email profile https://www.googleapis.com/auth/drive.file';

export type DriveOperation = 'auth' | 'list' | 'search' | 'fetch' | 'export' | 'upload' | 'update' | 'store' | 'load' | 'rotate' | 'revoke';
export type GoogleDriveToken = { accessToken: string; refreshToken: string; idToken?: string; expiresAt: string; scope: string; tokenType: string };
type StoredEnvelope = { iv: string; tag: string; ciphertext: string };
type VaultRecord = { vault_id: string; user_id: string; organization_id: string; provider: 'google-drive'; encrypted_token: StoredEnvelope; token_identifier: string; created_at: string; rotated_at: string | null; revoked_at: string | null };
type Vault = Record<string, VaultRecord>;

export type DriveEvidenceReceipt = {
  evidence_id: string; event_id: string; actor_id: string; organization_id: string; provider: 'google-drive'; operation: DriveOperation;
  file_id: string | null; revision_id: string | null; timestamp: string; input_digest: string | null; output_digest: string | null;
  request_metadata: { query: string | null; mime_type: string | null; token_identifier?: string; scopes?: string[] };
  response_metadata: { count: number | null; mime_type: string | null; file_ids?: string[] };
  temporal_interval: { start: string; end: string; semantics: 'half-open' };
  lineage: { node_id: string; predecessor_id: string | null };
  replay_receipt: { version: '1.0'; canonicalization: 'ceip-jcs-nfc-v1'; canonical_hash: string; signature: string | null };
};

function required(name: string): string { const value = process.env[name]?.trim(); if (!value) throw new Error(`GOOGLE_DRIVE: ${name} is not configured`); return value; }
function clientId() { return required('GOOGLE_CLIENT_ID'); }
function clientSecret() { return required('GOOGLE_CLIENT_SECRET'); }
function redirectUri() { return process.env.GOOGLE_DRIVE_REDIRECT_URI?.trim() || 'http://localhost:3000/api/integrations/google-drive/callback'; }
function scopes() { return (process.env.GOOGLE_DRIVE_SCOPES ?? DEFAULT_SCOPES).split(/[ ,]+/).map(v => v.trim()).filter(Boolean); }
function stateKey() { return createHash('sha256').update(required('GOOGLE_DRIVE_STATE_SECRET')).digest(); }
function masterVaultKey() { return createHash('sha256').update(required('GOOGLE_DRIVE_TOKEN_KEY')).digest(); }
function vaultPath() { return process.env.GOOGLE_DRIVE_TOKEN_VAULT?.trim() || path.resolve(process.cwd(), '.local', 'google-drive', 'tokens.json'); }
function evidencePath() { return process.env.GOOGLE_DRIVE_EVIDENCE_LOG?.trim() || path.resolve(process.cwd(), '.local', 'google-drive', 'evidence.jsonl'); }
function vaultIndex(actorId: string, organizationId: string) { return `${organizationId}:${actorId}`; }
function tenantKey(actorId: string, organizationId: string) { return createHmac('sha256', masterVaultKey()).update(vaultIndex(actorId, organizationId).normalize('NFC')).digest(); }

export function canonicalize(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value.normalize('NFC'));
  if (typeof value === 'number') { if (!Number.isFinite(value)) throw new Error('HALT:CANONICALIZATION_ERROR'); return JSON.stringify(value); }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`;
  if (typeof value === 'object') return `{${Object.entries(value as Record<string, unknown>).filter(([,v]) => v !== undefined).sort(([a],[b]) => a.localeCompare(b)).map(([k,v]) => `${JSON.stringify(k.normalize('NFC'))}:${canonicalize(v)}`).join(',')}}`;
  throw new Error('HALT:CANONICALIZATION_ERROR');
}
function sha256(value: unknown) { return createHash('sha256').update(canonicalize(value)).digest('hex'); }
function tokenIdentifier(token: string) { return `gdrv_${createHash('sha256').update(token).digest('hex').slice(0, 24)}`; }

function encodeState(payload: Record<string, string>) { const body = Buffer.from(JSON.stringify(payload)).toString('base64url'); return `${body}.${createHmac('sha256', stateKey()).update(body).digest('base64url')}`; }
function decodeState(state: string) {
  const [body, signature] = state.split('.'); if (!body || !signature) throw new Error('HALT:AUTHORITY_ERROR invalid OAuth state');
  const expected = createHmac('sha256', stateKey()).update(body).digest(); const actual = Buffer.from(signature, 'base64url');
  if (actual.length !== expected.length || !timingSafeEqual(actual, expected)) throw new Error('HALT:AUTHORITY_ERROR invalid OAuth state');
  const payload = JSON.parse(Buffer.from(body, 'base64url').toString()) as Record<string,string>;
  if (Date.now() - Date.parse(payload.issuedAt ?? '') > 600_000) throw new Error('HALT:AUTHORITY_ERROR expired OAuth state'); return payload;
}
function encrypt(token: GoogleDriveToken, actorId: string, organizationId: string): StoredEnvelope { const iv=randomBytes(12); const cipher=createCipheriv('aes-256-gcm',tenantKey(actorId,organizationId),iv); const ciphertext=Buffer.concat([cipher.update(JSON.stringify(token)),cipher.final()]); return {iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')}; }
function decrypt(record: VaultRecord): GoogleDriveToken { const decipher=createDecipheriv('aes-256-gcm',tenantKey(record.user_id,record.organization_id),Buffer.from(record.encrypted_token.iv,'base64')); decipher.setAuthTag(Buffer.from(record.encrypted_token.tag,'base64')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(record.encrypted_token.ciphertext,'base64')),decipher.final()]).toString()) as GoogleDriveToken; }
async function loadVault(): Promise<Vault> { try { return JSON.parse(await readFile(vaultPath(),'utf8')) as Vault; } catch(e) { if ((e as NodeJS.ErrnoException).code==='ENOENT') return {}; throw new Error('HALT:AUTHORITY_ERROR vault unavailable'); } }
async function saveVault(vault: Vault) { const target=vaultPath(); await mkdir(path.dirname(target),{recursive:true}); const temp=`${target}.${process.pid}.tmp`; await writeFile(temp,`${JSON.stringify(vault,null,2)}\n`,{mode:0o600}); await rename(temp,target); }

const predecessors = new Map<string,string>();
const accessTokens = new Map<string, { value: string; expiresAt: string }>();
async function recordEvidence(input: { actorId:string; organizationId:string; operation:DriveOperation; fileId?:string; revisionId?:string; request?:unknown; output?:unknown; query?:string; mimeType?:string; count?:number; fileIds?:string[]; tokenId?:string; scopes?:string[] }): Promise<DriveEvidenceReceipt> {
  if (!input.actorId || !input.organizationId) throw new Error('HALT:AUTHORITY_ERROR actor and organization binding required');
  const start=new Date().toISOString(); const lineageKey=`${input.organizationId}:${input.fileId ?? input.operation}`; const eventId=`evt_${randomBytes(16).toString('hex')}`;
  const base = { evidence_id:`ev_${randomBytes(16).toString('hex')}`, event_id:eventId, actor_id:input.actorId, organization_id:input.organizationId, provider:'google-drive' as const, operation:input.operation, file_id:input.fileId ?? null, revision_id:input.revisionId ?? null, timestamp:start, input_digest:input.request===undefined?null:sha256(input.request), output_digest:input.output===undefined?null:sha256(input.output), request_metadata:{query:input.query ?? null,mime_type:input.mimeType ?? null,...(input.tokenId?{token_identifier:input.tokenId}:{}),...(input.scopes?{scopes:input.scopes}: {})}, response_metadata:{count:input.count ?? null,mime_type:input.mimeType ?? null,...(input.fileIds?{file_ids:input.fileIds}: {})}, temporal_interval:{start,end:new Date().toISOString(),semantics:'half-open' as const}, lineage:{node_id:eventId,predecessor_id:predecessors.get(lineageKey) ?? null} };
  const receipt: DriveEvidenceReceipt={...base,replay_receipt:{version:'1.0',canonicalization:'ceip-jcs-nfc-v1',canonical_hash:sha256(base),signature:null}};
  try { await mkdir(path.dirname(evidencePath()),{recursive:true}); await appendFile(evidencePath(),`${canonicalize(receipt)}\n`,{encoding:'utf8',mode:0o600}); } catch { throw new Error('HALT:EVIDENCE_ERROR evidence append failed'); }
  predecessors.set(lineageKey,eventId); return receipt;
}

export async function storeGoogleDriveToken(actorId:string, organizationId:string, token:GoogleDriveToken, operation:'store'|'rotate'='store') { const vault=await loadVault(); const key=vaultIndex(actorId,organizationId); const prior=vault[key]; const now=new Date().toISOString(); const id=tokenIdentifier(token.refreshToken); accessTokens.set(key,{value:token.accessToken,expiresAt:token.expiresAt}); const persistent={...token,accessToken:''}; vault[key]={vault_id:prior?.vault_id ?? `vault_${randomBytes(16).toString('hex')}`,user_id:actorId,organization_id:organizationId,provider:'google-drive',encrypted_token:encrypt(persistent,actorId,organizationId),token_identifier:id,created_at:prior?.created_at ?? now,rotated_at:prior?now:null,revoked_at:null}; await saveVault(vault); await recordEvidence({actorId,organizationId,operation,tokenId:id}); }
async function loadGoogleDriveToken(actorId:string,organizationId:string) { const record=(await loadVault())[vaultIndex(actorId,organizationId)]; if (!record || record.revoked_at) throw new Error('HALT:AUTHORITY_ERROR Google Drive account is not connected'); const token=decrypt(record); await recordEvidence({actorId,organizationId,operation:'load',tokenId:record.token_identifier}); return {record,token}; }
export async function revokeGoogleDriveToken(actorId:string,organizationId:string) { const {record,token}=await loadGoogleDriveToken(actorId,organizationId); const response=await fetch(REVOKE_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:token.refreshToken})}); if (!response.ok) throw new Error(`HALT:AUTHORITY_ERROR Google revocation failed (${response.status})`); const vault=await loadVault(); vault[vaultIndex(actorId,organizationId)]={...record,encrypted_token:{iv:'',tag:'',ciphertext:''},revoked_at:new Date().toISOString()}; await saveVault(vault); accessTokens.delete(vaultIndex(actorId,organizationId)); await recordEvidence({actorId,organizationId,operation:'revoke',tokenId:record.token_identifier}); }
export async function googleDriveStatus(actorId:string,organizationId:string) { const record=(await loadVault())[vaultIndex(actorId,organizationId)]; if (!record || record.revoked_at) return {connected:false}; const token=decrypt(record); return {connected:true,vaultId:record.vault_id,expiresAt:token.expiresAt,scope:token.scope,createdAt:record.created_at,rotatedAt:record.rotated_at}; }

export function buildGoogleDriveAuthorization(actorId:string,organizationId:string,returnTo='/integrations/google-drive') { if(!actorId||!organizationId) throw new Error('HALT:AUTHORITY_ERROR actor and organization binding required'); const safe=returnTo.startsWith('/')&&!returnTo.startsWith('//')?returnTo:'/integrations/google-drive'; const state=encodeState({actorId,organizationId,returnTo:safe,issuedAt:new Date().toISOString(),nonce:randomBytes(16).toString('hex')}); const params=new URLSearchParams({client_id:clientId(),redirect_uri:redirectUri(),response_type:'code',scope:scopes().join(' '),state,access_type:'offline',include_granted_scopes:'true',prompt:'consent'}); return {authorizationUrl:`${AUTHORIZATION_URL}?${params}`,redirectUri:redirectUri()}; }

export async function validateGoogleIdToken(idToken:string, fetcher:typeof fetch=fetch) { const [headerRaw,payloadRaw,signatureRaw]=idToken.split('.'); if(!headerRaw||!payloadRaw||!signatureRaw) throw new Error('HALT:AUTHORITY_ERROR invalid ID token'); const header=JSON.parse(Buffer.from(headerRaw,'base64url').toString()) as {alg?:string;kid?:string}; const payload=JSON.parse(Buffer.from(payloadRaw,'base64url').toString()) as {iss?:string;aud?:string|string[];exp?:number;sub?:string}; const audiences=Array.isArray(payload.aud)?payload.aud:[payload.aud]; if(header.alg!=='RS256'||!['accounts.google.com','https://accounts.google.com'].includes(payload.iss??'')||!audiences.includes(clientId())||!payload.exp||payload.exp*1000<=Date.now()||!payload.sub) throw new Error('HALT:AUTHORITY_ERROR ID token claims invalid'); const certs=await (await fetcher(GOOGLE_CERTS_URL)).json() as {keys:Array<Record<string,unknown> & {kid?:string}>}; const jwk=certs.keys.find(k=>k.kid===header.kid); if(!jwk||!verify('RSA-SHA256',Buffer.from(`${headerRaw}.${payloadRaw}`),createPublicKey({key:jwk as never,format:'jwk'}),Buffer.from(signatureRaw,'base64url'))) throw new Error('HALT:AUTHORITY_ERROR ID token signature invalid'); return payload; }

export async function completeGoogleDriveAuthorization(code:string,state:string) { const payload=decodeState(state); const response=await fetch(TOKEN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId(),client_secret:clientSecret(),code,grant_type:'authorization_code',redirect_uri:redirectUri()})}); const data=await response.json() as Record<string,unknown>; if(!response.ok) throw new Error(`HALT:AUTHORITY_ERROR token exchange failed (${response.status})`); const refreshToken=String(data.refresh_token??''); const idToken=String(data.id_token??''); if(!refreshToken||!idToken) throw new Error('HALT:AUTHORITY_ERROR refresh token and ID token required'); await validateGoogleIdToken(idToken); const token={accessToken:String(data.access_token??''),refreshToken,idToken,expiresAt:new Date(Date.now()+Number(data.expires_in??3600)*1000).toISOString(),scope:String(data.scope??scopes().join(' ')),tokenType:String(data.token_type??'Bearer')}; await storeGoogleDriveToken(payload.actorId!,payload.organizationId!,token); const evidence=await recordEvidence({actorId:payload.actorId!,organizationId:payload.organizationId!,operation:'auth',scopes:token.scope.split(' ')}); return {actorId:payload.actorId,organizationId:payload.organizationId,returnTo:payload.returnTo||'/integrations/google-drive',evidenceId:evidence.evidence_id}; }

async function accessToken(actorId:string,organizationId:string) { const key=vaultIndex(actorId,organizationId); const cached=accessTokens.get(key); if(cached&&Date.parse(cached.expiresAt)>Date.now()+60_000)return cached.value; const {token}=await loadGoogleDriveToken(actorId,organizationId); const response=await fetch(TOKEN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId(),client_secret:clientSecret(),refresh_token:token.refreshToken,grant_type:'refresh_token'})}); const data=await response.json() as Record<string,unknown>; if(!response.ok) throw new Error(`HALT:AUTHORITY_ERROR token refresh failed (${response.status})`); const next={...token,accessToken:String(data.access_token??''),refreshToken:String(data.refresh_token??token.refreshToken),expiresAt:new Date(Date.now()+Number(data.expires_in??3600)*1000).toISOString(),scope:String(data.scope??token.scope)}; accessTokens.set(key,{value:next.accessToken,expiresAt:next.expiresAt}); if(data.refresh_token) await storeGoogleDriveToken(actorId,organizationId,next,'rotate'); return next.accessToken; }
async function driveRequest(actorId:string,organizationId:string,url:string,init?:RequestInit) { const response=await fetch(url,{...init,headers:{authorization:`Bearer ${await accessToken(actorId,organizationId)}`,...(init?.headers??{})}}); if(!response.ok) throw new Error(`GOOGLE_DRIVE: request failed (${response.status})`); return response; }

export async function listGoogleDriveFiles(actorId:string,organizationId:string,query?:string) { const params=new URLSearchParams({pageSize:'100',orderBy:'modifiedTime desc',fields:'files(id,name,mimeType,modifiedTime,createdTime,size,webViewLink,parents,version)'}); if(query)params.set('q',query); const result=await (await driveRequest(actorId,organizationId,`${DRIVE_URL}/files?${params}`)).json() as {files?:Array<{id?:string}>}; const files=result.files??[]; return {files,receipt:await recordEvidence({actorId,organizationId,operation:query?'search':'list',query,count:files.length,fileIds:files.map(f=>f.id??'').filter(Boolean),output:result})}; }
export async function getGoogleDriveFile(actorId:string,organizationId:string,fileId:string) { const fields='id,name,mimeType,modifiedTime,createdTime,size,webViewLink,parents,version,description'; const file=await (await driveRequest(actorId,organizationId,`${DRIVE_URL}/files/${encodeURIComponent(fileId)}?fields=${encodeURIComponent(fields)}`)).json() as {mimeType?:string;version?:string}; return {file,receipt:await recordEvidence({actorId,organizationId,operation:'fetch',fileId,revisionId:file.version,mimeType:file.mimeType,request:{fileId},output:file})}; }
export async function fetchGoogleDriveFile(actorId:string,organizationId:string,fileId:string,exportMimeType='application/pdf') { const {file}=await getGoogleDriveFile(actorId,organizationId,fileId); const native=String(file.mimeType??'').startsWith('application/vnd.google-apps.'); const url=native?`${DRIVE_URL}/files/${encodeURIComponent(fileId)}/export?mimeType=${encodeURIComponent(exportMimeType)}`:`${DRIVE_URL}/files/${encodeURIComponent(fileId)}?alt=media`; const response=await driveRequest(actorId,organizationId,url); const data=Buffer.from(await response.arrayBuffer()); const mimeType=response.headers.get('content-type')??(native?exportMimeType:String(file.mimeType??'application/octet-stream')); return {file,dataBase64:data.toString('base64'),mimeType,receipt:await recordEvidence({actorId,organizationId,operation:native?'export':'fetch',fileId,revisionId:file.version,mimeType,request:{fileId,exportMimeType},output:data.toString('base64')})}; }
function multipart(metadata:unknown,mimeType:string,data:Buffer) { const boundary=`aais_${randomBytes(12).toString('hex')}`; return {body:Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${mimeType}\r\n\r\n`),data,Buffer.from(`\r\n--${boundary}--`)]),contentType:`multipart/related; boundary=${boundary}`}; }
export async function uploadGoogleDriveFile(actorId:string,organizationId:string,input:{name:string;mimeType:string;data:Buffer;parentId?:string}) { const metadata={name:input.name,...(input.parentId?{parents:[input.parentId]}:{})}; const body=multipart(metadata,input.mimeType,input.data); const file=await (await driveRequest(actorId,organizationId,`${UPLOAD_URL}/files?uploadType=multipart&fields=id,name,mimeType,modifiedTime,webViewLink,version`,{method:'POST',headers:{'content-type':body.contentType},body:body.body})).json() as {id?:string;version?:string}; return {file,receipt:await recordEvidence({actorId,organizationId,operation:'upload',fileId:file.id,revisionId:file.version,mimeType:input.mimeType,request:{name:input.name,data:input.data.toString('base64')},output:file})}; }
export async function updateGoogleDriveFile(actorId:string,organizationId:string,fileId:string,input:{name?:string;mimeType:string;data:Buffer}) { const body=multipart(input.name?{name:input.name}:{},input.mimeType,input.data); const file=await (await driveRequest(actorId,organizationId,`${UPLOAD_URL}/files/${encodeURIComponent(fileId)}?uploadType=multipart&fields=id,name,mimeType,modifiedTime,webViewLink,version`,{method:'PATCH',headers:{'content-type':body.contentType},body:body.body})).json() as {id?:string;version?:string}; return {file,receipt:await recordEvidence({actorId,organizationId,operation:'update',fileId,revisionId:file.version,mimeType:input.mimeType,request:{fileId,data:input.data.toString('base64')},output:file})}; }
export async function createGoogleDriveTextFile(actorId:string,organizationId:string,input:{name:string;content:string;mimeType?:string;parentId?:string}) { return uploadGoogleDriveFile(actorId,organizationId,{name:input.name,mimeType:input.mimeType??'text/plain',data:Buffer.from(input.content),parentId:input.parentId}); }
