"""Continuity governance stack: CCS, Proof, CVR, and substrate."""

from src.continuity.ccs import (
    CCSStore,
    ContinuityTrace,
    build_store_from_scenario,
    continuity_trace_fingerprint,
    load_scenario,
    replay_trace_from_store,
    trace_from_object,
)
from src.continuity.pipeline import run_proof_pipeline
from src.continuity.pod import PODDecision
from src.continuity.proof import Proof, ProofStatus, create_proof, revoke_proof, valid_proof
from src.continuity.reputation import (
    ContinuityReputation,
    ContinuityValidatedReputation,
    compute_cvr,
    compute_derived_score,
    ReputationWeights,
    DEFAULT_REPUTATION_WEIGHTS,
    EXAMPLE_REPUTATION_WEIGHTS,
)
from src.continuity.trace_v1 import ContinuityMetrics, ContinuityTraceV1, project_trace_v1
from src.continuity.substrate import ContinuitySubstrate, substrate_from_store, validate_substrate
from src.continuity.ugr_trace import evaluate_trace_ugr_invariants, valid_continuity_trace
from src.continuity.cab import (
    AssumptionRecord,
    CABLedger,
    CABLedgerEntry,
    CABObjectType,
    ContinuityReceipt,
    DecisionRecord,
    EvidenceChain,
    FounderKnowledgeSnapshot,
    IntentRecord,
    ReconstructionPlan,
    SuccessionProtocol,
    ingest_ciems_transformation_event,
    ingest_neomundi_measurement,
    ingest_nova_continuity_governance,
    load_cab_scenario,
    populate_ledger_from_scenario,
)
from src.continuity.cab_invariants import CABInvariantReport, evaluate_cab_invariants
from src.continuity.constitutional_apply import apply_constitutional_chain
from src.continuity.constitutional_chain import (
    CONSTITUTIONAL_CHAIN,
    OPERATORS_MANUAL_TEXT,
    OPERATORS_OATH_TEXT,
    ROOT_00X,
    ROOT_00Y,
    ROOT_00Y_CANONICAL_TEXT,
    ROOT_00Z,
    ROOT_00Z_CANONICAL_TEXT,
    ROOT_015,
    ROOT_015_CANONICAL_TEXT,
    UGR_C10_CANONICAL_TEXT,
    UGR_C11_CANONICAL_TEXT,
    UGR_C12_CANONICAL_TEXT,
    UGR_CONSTITUTION_ASSEMBLED_TEXT,
    UGR_C9_CANONICAL_TEXT,
    UGR_PREAMBLE_TEXT,
    chain_index,
)
from src.continuity.inheritance import (
    OperatorState,
    operator_state_from_lineage,
    validate_operator_succession,
)
from src.continuity.constitutional_kernel import (
    ConstitutionalKernel,
    DEFAULT_CONSTITUTIONAL_KERNEL,
    KERNEL_ID,
    NK_0001_CANONICAL_TEXT,
    GuardResult,
    KernelViolation,
    continuity_guard,
    convergence_guard,
    creation_guard,
    evaluate_transition_guards,
    invariant_guard,
    run_kernel_enforcement_proof,
    temporal_guard,
)
from src.continuity.inter_civilizational import (
    Civilization,
    cross_civilizational_fitness,
    evaluate_interoperability,
)
from src.continuity.temporal_governance import (
    TemporalState,
    evaluate_temporal_coherence,
    temporal_convergence_fitness,
)
from src.continuity.convergence_algebra import (
    CONVERGE_CAPABILITY_ID,
    ConvergenceProof,
    DEFAULT_DELTA_MAX,
    converge_many,
    converge_pair,
    convergence_fitness,
    d_conv,
    fitness_within_tolerance,
)
from src.continuity.governed_evolution import (
    DEFAULT_S_MIN,
    evaluate_stewardship,
    governed_evolution_admissible,
    stewardship_score,
    validate_lineage_evolution,
)
from src.continuity.continuity_lattice import lci_holds, trace_join, trace_leq
from src.continuity.creation_operator import CreationOperator, LCIViolation, SubstrateState
from src.continuity.lci_stack import apply_lci_stack
from src.continuity.lineage import Lineage, continuity_trace, generativity
from src.continuity.universal_semantics import (
    DEFAULT_META_LATTICE,
    DEFAULT_UNIVERSAL_FIELD,
    MetaUniversalLattice,
    UniversalField,
    verify_meaning,
)

__all__ = [
    "CCSStore",
    "AssumptionRecord",
    "CABInvariantReport",
    "CABLedger",
    "CABLedgerEntry",
    "CABObjectType",
    "ContinuityReputation",
    "ContinuityReceipt",
    "ContinuitySubstrate",
    "ContinuityTrace",
    "ContinuityValidatedReputation",
    "DecisionRecord",
    "EvidenceChain",
    "FounderKnowledgeSnapshot",
    "IntentRecord",
    "OperatorState",
    "PODDecision",
    "Proof",
    "ProofStatus",
    "ReconstructionPlan",
    "ROOT_00X",
    "ROOT_00Y",
    "ROOT_00Y_CANONICAL_TEXT",
    "ROOT_00Z",
    "ROOT_00Z_CANONICAL_TEXT",
    "ROOT_015",
    "ROOT_015_CANONICAL_TEXT",
    "build_store_from_scenario",
    "compute_cvr",
    "compute_derived_score",
    "ContinuityMetrics",
    "ContinuityTraceV1",
    "ReputationWeights",
    "DEFAULT_REPUTATION_WEIGHTS",
    "EXAMPLE_REPUTATION_WEIGHTS",
    "SuccessionProtocol",
    "operator_state_from_lineage",
    "project_trace_v1",
    "continuity_trace_fingerprint",
    "create_proof",
    "evaluate_cab_invariants",
    "evaluate_trace_ugr_invariants",
    "ingest_ciems_transformation_event",
    "ingest_neomundi_measurement",
    "ingest_nova_continuity_governance",
    "load_scenario",
    "load_cab_scenario",
    "populate_ledger_from_scenario",
    "replay_trace_from_store",
    "revoke_proof",
    "run_proof_pipeline",
    "substrate_from_store",
    "trace_from_object",
    "valid_continuity_trace",
    "valid_proof",
    "validate_substrate",
    "Civilization",
    "CONVERGE_CAPABILITY_ID",
    "ConvergenceProof",
    "CONSTITUTIONAL_CHAIN",
    "CreationOperator",
    "DEFAULT_DELTA_MAX",
    "DEFAULT_META_LATTICE",
    "DEFAULT_S_MIN",
    "DEFAULT_UNIVERSAL_FIELD",
    "LCIViolation",
    "Lineage",
    "MetaUniversalLattice",
    "ConstitutionalKernel",
    "DEFAULT_CONSTITUTIONAL_KERNEL",
    "GuardResult",
    "KERNEL_ID",
    "KernelViolation",
    "NK_0001_CANONICAL_TEXT",
    "OPERATORS_MANUAL_TEXT",
    "OPERATORS_OATH_TEXT",
    "SubstrateState",
    "TemporalState",
    "UGR_C12_CANONICAL_TEXT",
    "UGR_CONSTITUTION_ASSEMBLED_TEXT",
    "UGR_C10_CANONICAL_TEXT",
    "UGR_C11_CANONICAL_TEXT",
    "UGR_C9_CANONICAL_TEXT",
    "UGR_PREAMBLE_TEXT",
    "UniversalField",
    "apply_lci_stack",
    "apply_constitutional_chain",
    "chain_index",
    "converge_many",
    "converge_pair",
    "convergence_fitness",
    "continuity_trace",
    "d_conv",
    "continuity_guard",
    "convergence_guard",
    "creation_guard",
    "cross_civilizational_fitness",
    "evaluate_transition_guards",
    "invariant_guard",
    "run_kernel_enforcement_proof",
    "temporal_guard",
    "evaluate_interoperability",
    "evaluate_stewardship",
    "evaluate_temporal_coherence",
    "fitness_within_tolerance",
    "generativity",
    "governed_evolution_admissible",
    "lci_holds",
    "stewardship_score",
    "temporal_convergence_fitness",
    "trace_join",
    "trace_leq",
    "validate_lineage_evolution",
    "validate_operator_succession",
    "verify_meaning",
]
