/** Fault codes aligned with Python `src/fault_journal.py`. */

export const FAULT_CODE_INVARIANT_BREACH = 'INVARIANT_BREACH' as const;
export const FAULT_CODE_BRIDGE_BINDING_MISMATCH = 'BRIDGE_BINDING_MISMATCH' as const;
export const FAULT_CODE_AUTHORITY_MISMATCH = 'AUTHORITY_MISMATCH' as const;
export const FAULT_CODE_SPAN_ORPHAN = 'SPAN_ORPHAN' as const;
export const FAULT_CODE_RUNTIME_TIMEOUT = 'RUNTIME_TIMEOUT' as const;
export const FAULT_CODE_TRUST_ROOT_MISMATCH = 'TRUST_ROOT_MISMATCH' as const;
export const FAULT_CODE_ATTESTATION_REFUSED = 'ATTESTATION_REFUSED' as const;
export const FAULT_CODE_CORRIDOR_ADMISSION_DENIED = 'CORRIDOR_ADMISSION_DENIED' as const;
export const FAULT_CODE_RUNTIME_INITIALIZATION_DENIED = 'RUNTIME_INITIALIZATION_DENIED' as const;

export const FAULT_CODES = [
  FAULT_CODE_INVARIANT_BREACH,
  FAULT_CODE_BRIDGE_BINDING_MISMATCH,
  FAULT_CODE_AUTHORITY_MISMATCH,
  FAULT_CODE_SPAN_ORPHAN,
  FAULT_CODE_RUNTIME_TIMEOUT,
  FAULT_CODE_TRUST_ROOT_MISMATCH,
  FAULT_CODE_ATTESTATION_REFUSED,
  FAULT_CODE_CORRIDOR_ADMISSION_DENIED,
  FAULT_CODE_RUNTIME_INITIALIZATION_DENIED,
] as const;

export type FaultCode = (typeof FAULT_CODES)[number];
